# Generated by Django 5.0.1 on 2026-04-20 04:50

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_id', models.UUIDField(verbose_name='ID sản phẩm')),
                ('user_id', models.UUIDField(verbose_name='ID người dùng')),
                ('order_id', models.UUIDField(blank=True, null=True, verbose_name='ID đơn hàng')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Đánh giá')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Tiêu đề')),
                ('content', models.TextField(verbose_name='Nội dung')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Đã xác minh mua hàng')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Hiển thị')),
                ('helpful_count', models.IntegerField(default=0, verbose_name='Lượt hữu ích')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'reviews',
                'ordering': ['-created_at'],
                'unique_together': {('product_id', 'user_id')},
            },
        ),
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='reviews/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='review_app.review')),
            ],
            options={
                'db_table': 'review_images',
            },
        ),
        migrations.CreateModel(
            name='ReviewReply',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('content', models.TextField()),
                ('is_seller', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='review_app.review')),
            ],
            options={
                'db_table': 'review_replies',
            },
        ),
    ]
