# Generated by Django 5.0.1 on 2026-04-20 04:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_id', models.UUIDField(verbose_name='ID đơn hàng')),
                ('tracking_number', models.CharField(max_length=50, unique=True, verbose_name='Mã vận đơn')),
                ('carrier', models.CharField(default='Giao hàng nhanh', max_length=100, verbose_name='Đơn vị vận chuyển')),
                ('status', models.CharField(choices=[('pending', 'Chờ lấy hàng'), ('picked_up', 'Đã lấy hàng'), ('in_transit', 'Đang vận chuyển'), ('out_for_delivery', 'Đang giao hàng'), ('delivered', 'Đã giao'), ('failed', 'Giao thất bại'), ('returned', 'Đã hoàn trả')], default='pending', max_length=20)),
                ('recipient_name', models.CharField(max_length=255)),
                ('recipient_phone', models.CharField(max_length=15)),
                ('shipping_address', models.TextField()),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('shipping_fee', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('estimated_delivery', models.DateField(blank=True, null=True)),
                ('actual_delivery', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'shipments',
            },
        ),
        migrations.CreateModel(
            name='TrackingEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=20)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='shipping_app.shipment')),
            ],
            options={
                'db_table': 'tracking_events',
                'ordering': ['-created_at'],
            },
        ),
    ]
