# Generated by Django 5.0.1 on 2026-04-20 04:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_id', models.UUIDField(verbose_name='ID đơn hàng')),
                ('user_id', models.UUIDField(verbose_name='ID người dùng')),
                ('transaction_id', models.CharField(max_length=100, unique=True, verbose_name='Mã giao dịch')),
                ('method', models.CharField(choices=[('momo', 'Ví MoMo'), ('vnpay', 'VNPay'), ('cod', 'Thanh toán khi nhận hàng'), ('bank_transfer', 'Chuyển khoản')], max_length=20, verbose_name='Phương thức')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Số tiền')),
                ('currency', models.CharField(default='VND', max_length=3, verbose_name='Tiền tệ')),
                ('status', models.CharField(choices=[('pending', 'Chờ thanh toán'), ('processing', 'Đang xử lý'), ('completed', 'Thành công'), ('failed', 'Thất bại'), ('cancelled', 'Đã hủy'), ('refunded', 'Đã hoàn tiền')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('provider_transaction_id', models.CharField(blank=True, max_length=100, verbose_name='Mã GD nhà cung cấp')),
                ('provider_response', models.JSONField(default=dict, verbose_name='Response nhà cung cấp')),
                ('payment_url', models.URLField(blank=True, verbose_name='URL thanh toán')),
                ('return_url', models.URLField(blank=True, verbose_name='URL trả về')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian thanh toán')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'db_table': 'payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('refund_id', models.CharField(max_length=100, unique=True, verbose_name='Mã hoàn tiền')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Số tiền')),
                ('reason', models.TextField(verbose_name='Lý do')),
                ('status', models.CharField(choices=[('pending', 'Chờ xử lý'), ('processing', 'Đang xử lý'), ('completed', 'Hoàn thành'), ('failed', 'Thất bại')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('provider_response', models.JSONField(default=dict, verbose_name='Response nhà cung cấp')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày hoàn thành')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='payment_app.payment')),
            ],
            options={
                'db_table': 'refunds',
            },
        ),
    ]
