# Generated by Django 5.0.1 on 2026-04-20 04:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Mã template')),
                ('type', models.CharField(max_length=20, verbose_name='Loại')),
                ('title_template', models.CharField(max_length=255, verbose_name='Template tiêu đề')),
                ('message_template', models.TextField(verbose_name='Template nội dung')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notification_templates',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(verbose_name='ID người dùng')),
                ('type', models.CharField(choices=[('order', 'Đơn hàng'), ('payment', 'Thanh toán'), ('shipping', 'Vận chuyển'), ('promotion', 'Khuyến mãi'), ('system', 'Hệ thống')], max_length=20, verbose_name='Loại')),
                ('channel', models.CharField(choices=[('in_app', 'Trong ứng dụng'), ('email', 'Email'), ('sms', 'SMS'), ('push', 'Push notification')], default='in_app', max_length=20, verbose_name='Kênh')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề')),
                ('message', models.TextField(verbose_name='Nội dung')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Dữ liệu bổ sung')),
                ('is_read', models.BooleanField(default=False, verbose_name='Đã đọc')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian đọc')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id', '-created_at'], name='notificatio_user_id_611c58_idx'), models.Index(fields=['user_id', 'is_read'], name='notificatio_user_id_a4dd5c_idx')],
            },
        ),
    ]
